from __future__ import annotations

from typing import Any, Dict, List, Optional


def build_oracle_event_payload(
    *,
    problem_hash: str,
    trainability_class: str,
    candidate_family_pool: List[str],
    selected_family_ids: List[str],
    selector_version: str,
    propensity: float,
    certification_route: str,
    verifier_provenance: Optional[Dict[str, Any]],
    decision: str,
    artifact_kind: str,
    cost: Dict[str, Any],
    certified_count: int = 0,
    certified_target_count: int = 0,
    cert_ratio: float = 0.0,
    reward: float = 0.0,
    reward_reason: str = "",
    failure_stage: str = "",
    failure_subtype: str = "",
    checker_fallback_used: bool = False,
    solver_attempt_count: int = 0,
    selected_template_name: str = "",
    prompt_char_stats: Optional[Dict[str, int]] = None,
    compact_retry_count: int = 0,
    evidence: Optional[Dict[str, Any]] = None,
    memory_mode: str = "off",
    policy_version: str = "rule_v1",
    candidate_action_set: Optional[List[str]] = None,
    selected_action: str = "",
    exploration_flag: bool = False,
) -> Dict[str, Any]:
    return {
        "problem_hash": problem_hash,
        "trainability_class": trainability_class,
        "candidate_family_pool": candidate_family_pool,
        "selected_family_ids": selected_family_ids,
        "selector_version": selector_version,
        "propensity": propensity,
        "certification_route": certification_route,
        "verifier_provenance": verifier_provenance,
        "decision": decision,
        "artifact_kind": artifact_kind,
        "certified_count": certified_count,
        "certified_target_count": certified_target_count,
        "cert_ratio": cert_ratio,
        "reward": reward,
        "reward_reason": reward_reason,
        "failure_stage": failure_stage,
        "failure_subtype": failure_subtype,
        "checker_fallback_used": checker_fallback_used,
        "solver_attempt_count": solver_attempt_count,
        "selected_template_name": selected_template_name,
        "prompt_char_stats": prompt_char_stats or {},
        "compact_retry_count": compact_retry_count,
        "memory_mode": memory_mode,
        "policy_version": policy_version,
        "candidate_action_set": candidate_action_set or [],
        "selected_action": selected_action,
        "exploration_flag": exploration_flag,
        "cost": cost,
        "evidence": evidence or {},
    }
