"""
Mirror of :func:`src.graph.state.create_initial_state` as a plain ``dict``.

Used so this package can be imported without pulling in ``langgraph`` (via ``state.py``).
Keep in sync with ``src/graph/state.py`` when fields required by ``abstract_problem`` / codegen change.
"""

from __future__ import annotations

from typing import Any, Dict


def create_initial_state_dict(raw_problem: Dict[str, Any], config: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "raw_problem": raw_problem,
        "config": config,
        "problem": {
            "description": raw_problem.get("description", ""),
            "types": [],
            "constraints": {
                "time_limit": raw_problem.get("time_limit"),
                "space_limit": raw_problem.get("space_limit"),
            },
            "public_tests": raw_problem.get("public_tests", []),
            "retrieved_knowledge": [],
            "canonical": {},
            "tags_selected": [],
            "tags_level2_selected": [],
            "abstract_confidence": 0.0,
            "abstract_trace": {},
        },
        "plan": {
            "solution_plan": {},
            "algorithm_choice": "",
            "implementation_steps": [],
            "memory_item_ids": [],
            "memory_advice": "",
            "solver_graph_augmentation_block": "",
            "skill_selection_skill_ids": [],
            "skill_selection_subproblem_dag": {},
            "skill_selection_skills_content_md": "",
        },
        "solution": {
            "code": "",
            "version": 0,
            "compilation_success": False,
            "compilation_errors": [],
            "executable_path": None,
            "memory_item_ids": [],
            "diagnostic_mode": False,
        },
        "oracle_solution": None,
        "buggy_solution": None,
        "tests": {
            "generated_tests": [],
            "total_tests": 0,
            "test_results": [],
            "passed_tests": 0,
            "pass_rate": 0.0,
            "pending_execution": False,
            "ready": False,
            "checker_exe": None,
            "validator_exe": None,
            "oracle_route": None,
            "accepted_artifact_kind": None,
            "verifier_provenance": None,
            "certification_evidence": [],
            "cert_ratio": 0.0,
            "certified_count": 0,
            "certified_target_count": 0,
            "oracle_primary_family_id": None,
            "oracle_fallback_family_id": None,
            "oracle_selected_family_id": None,
            "candidate_family_pool": [],
            "oracle_compile_success": False,
            "oracle_public_self_check_pass": False,
            "oracle_probe_pack_pass": False,
            "checker_fallback_used": False,
            "solver_attempt_count": 0,
            "selected_template_name": None,
            "prompt_char_stats": {},
            "compact_retry_count": 0,
        },
        "feedback": {"feedback": {}, "suggested_fixes": []},
        "oracle_event_metadata": {},
        "oracle_memory_decision": {},
        "messages": [],
        "iteration": 0,
        "max_iterations": config.get("max_iterations", 5),
        "status": "pending",
        "hack_round": 0,
        "max_hack_rounds": config.get("max_hack_rounds", 3),
        "hack_passed": False,
        "hack_failures": [],
        "hacker_reward": 0.0,
        "hacker_memory_item_ids": [],
        "oracle_memory_item_ids": [],
        "analyst_report": {},
        "validator_rejection_reasons": [],
        "hack_result": "",
        "generator_route_used": "",
        "hack_failure_type": "",
        "generator_failure_kind": "",
        "generator_failure_reason": "",
        "current_phase": "TESTGEN",
        "execution_log": [],
        "llm_calls": 0,
        "prompt_tokens": 0,
        "completion_tokens": 0,
        "token_usage_source": "untracked",
    }
